### ISSUE TITLE
Running the Psychoacoustic Filtering script

### ISSUE THREAD

**Issue by RershallzzZ** [RUB-SysSec/dompteur#2]
Hello, I only want to use the psychoacoustic filter. Do I need to install the complete docker environment? Thanks.

**Comment by thorsten-e** [comment]
That should be possible, but you need to install the MATLAB runtime environment for computing the hearing thresholds. Since this might be interesting for a larger audience, we added an additional container that only includes necessary components (cf. `standalone-psychoacoustic-filtering`). For usage without docker you can just repeat the steps in the Dockerfile to setup the environment (+ fix any paths).
